# Generated by Django 3.1.4 on 2021-01-11 08:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthDay', models.DateField(default=None, verbose_name='Birthday')),
                ('phoneNumber', models.PositiveBigIntegerField(default=0)),
                ('account_type', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateField(auto_now=True, verbose_name='schedule day')),
                ('start_time', models.TimeField(default=datetime.time(8, 0), verbose_name='')),
                ('end_time', models.TimeField(default=datetime.time(2, 0), verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='system.person')),
                ('salary', models.IntegerField(default=0)),
                ('department', models.CharField(default='', max_length=100)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.schedule')),
            ],
            options={
                'abstract': False,
            },
            bases=('system.person',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='system.person')),
                ('height', models.IntegerField()),
                ('weight', models.FloatField()),
            ],
            bases=('system.person',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_price', models.IntegerField(default=0)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.service')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.service')),
            ],
        ),
        migrations.CreateModel(
            name='RadiologySpecialist',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='system.person')),
                ('salary', models.IntegerField(default=0)),
                ('specialization', models.CharField(default='', max_length=100)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.schedule')),
            ],
            options={
                'abstract': False,
            },
            bases=('system.person',),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_describtion', models.TextField(max_length=1000)),
                ('medical_problems', models.TextField(max_length=1000)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabSpecialist',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='system.person')),
                ('salary', models.IntegerField(default=0)),
                ('specialization', models.CharField(default='', max_length=100)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.schedule')),
            ],
            options={
                'abstract': False,
            },
            bases=('system.person',),
        ),
        migrations.CreateModel(
            name='HospitalManager',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='system.person')),
                ('salary', models.IntegerField(default=0)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.schedule')),
            ],
            options={
                'abstract': False,
            },
            bases=('system.person',),
        ),
        migrations.CreateModel(
            name='FrontdeskEmployee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='system.person')),
                ('salary', models.IntegerField(default=0)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.schedule')),
            ],
            options={
                'abstract': False,
            },
            bases=('system.person',),
        ),
        migrations.CreateModel(
            name='FinanceEmployee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='system.person')),
                ('salary', models.IntegerField(default=0)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.schedule')),
            ],
            options={
                'abstract': False,
            },
            bases=('system.person',),
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=1000)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyEmployee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='system.person')),
                ('salary', models.IntegerField(default=0)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.schedule')),
            ],
            options={
                'abstract': False,
            },
            bases=('system.person',),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, verbose_name='Appointment Date')),
                ('startTime', models.TimeField(default=datetime.time(8, 0), verbose_name='start time')),
                ('is_booked', models.BooleanField(default=False)),
                ('is_payed', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='system.schedule')),
                ('service', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.service')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.patient')),
            ],
            options={
                'ordering': ['startTime'],
            },
        ),
    ]
