# Generated by Django 3.1.4 on 2021-01-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phoneNumber',
            field=models.CharField(max_length=11),
        ),
    ]
