# Generated by Django 3.1.4 on 2021-01-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_taken', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='Hospital_name',
            new_name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='labspecialist',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='radiologyspecialist',
            name='specialization',
        ),
    ]
