# Generated by Django 3.1.4 on 2021-01-11 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20210111_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.hospitalmanager'),
        ),
        migrations.AddField(
            model_name='room',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.service'),
        ),
        migrations.AlterField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.service'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.schedule'),
        ),
        migrations.AlterField(
            model_name='emergencyemployee',
            name='schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.schedule'),
        ),
        migrations.AlterField(
            model_name='financeemployee',
            name='schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.schedule'),
        ),
        migrations.AlterField(
            model_name='frontdeskemployee',
            name='schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.schedule'),
        ),
        migrations.AlterField(
            model_name='hospitalmanager',
            name='schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.schedule'),
        ),
        migrations.AlterField(
            model_name='labspecialist',
            name='schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.schedule'),
        ),
        migrations.AlterField(
            model_name='radiologyspecialist',
            name='schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.schedule'),
        ),
        migrations.AlterField(
            model_name='service',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.service'),
        ),
    ]
