# Generated by Django 3.1.4 on 2021-01-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20210111_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='max_capacity',
            field=models.IntegerField(default=1),
        ),
    ]
